spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/user?serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml,
  type-aliases-package: com.example.springbootcacheintegrat.mapper

logging:
  level:
    com.example.springbootcacheintegrat.mapper: debug

